Coding_Challenge/Models/Project.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coding_Challenge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.UserProjects = new HashSet<UserProject>();
        }
    
        public int id { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int Credits { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProject> UserProjects { get; set; }
    }
}

Coding_Challenge/Controllers/Project_Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Coding_Challenge.Models;
using Coding_Challenge.Models.ProjectViewModels;

namespace Coding_Challenge.Controllers
{
    public class Project_Controller : Controller
    {
        // Get: Project

        public ActionResult list_Project()
        {
            List<cls_ListProjectViewModel> lst;
            using (Coding_ChallengeEntities db = new Coding_ChallengeEntities())
            {
                lst = (from Obj_project in db.Projects
                       select new cls_ListProjectViewModel
                       {
                           iId = Obj_project.id,
                           dtStartDate = Obj_project.StartDate,
                           dtEndData = Obj_project.EndDate,
                           iCredits = Obj_project.Credits
                       }).ToList();
            }

            return View(lst);
        }

        public ActionResult Add_Project()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add_Project(cls_AddProjectViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (Coding_ChallengeEntities db = new Coding_ChallengeEntities())
                    {
                        var Obj_project = new Project();
                        Obj_project.StartDate = model.dtStartDate;
                        Obj_project.EndDate = model.dtEndData;
                        Obj_project.Credits = model.iCredits;


                        db.Projects.Add(Obj_project);
                        db.SaveChanges();
                    }

                    return Redirect("/Project_/list_Project");
                }

                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpGet]
        public ActionResult Delete_Project(int id)
        {
            using (Coding_ChallengeEntities db = new Coding_ChallengeEntities())
            {
                var Obj_Project = db.Projects.Find(id);
                db.Projects.Remove(Obj_Project);
                db.SaveChanges();
            }
            return Redirect("/Project_/list_Project");
        }
    }
}

Coding_Challenge/Views/Project_/Add_Project.cshtml
@model Coding_Challenge.Models.ProjectViewModels.cls_AddProjectViewModel
@{
    ViewBag.Title = "Add_Project";
}

<h2></h2>

@using (Html.BeginForm("Add_Project", "Project_", FormMethod.Post))
{
    <div class="row" style="margin: 50px;">
        <h2>Add a New Project</h2>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="row">
                @Html.LabelFor(d => d.dtStartDate)<br />
                @Html.EditorFor(d => d.dtStartDate, "", new { @class = "form-control" })<br />
                @Html.ValidationMessageFor(d => d.dtStartDate, null, new { @class = "red" })
            </div>
            <div class="row">
                @Html.LabelFor(d => d.iCredits)
                @Html.TextBoxFor(d => d.iCredits, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.iCredits, null, new { @class = "red" })
            </div>
            <div class="row">
                @Html.LabelFor(d => d.dtEndData)<br />
                @Html.EditorFor(d => d.dtEndData, "", new { @class = "form-control" })<br />
                @Html.ValidationMessageFor(d => d.dtEndData, null, new { @class = "red" })
            </div>
        </div>

        <div class="col-md-12" style="text-align:right;padding:5px">
            <input value="Save Project" type="submit" class="btn btn-primary" />
        </div>
    </div>
}

Coding_Challenge/Views/Project_/Delete_Project.cshtml
@{
    ViewBag.Title = "Delete_Project";
}

<h2>Delete_Project</h2>

Coding_Challenge/Views/Project_/list_Project.cshtml
@model List<Coding_Challenge.Models.ProjectViewModels.cls_ListProjectViewModel>
@{
    ViewBag.Title = "list_Project";
}

<div class="row" style="margin: 50px;">
    <h2>Projects</h2>
</div>


<div class="row" style="text-align:right; padding:5px">
    <a href="../Project_/Add_Project" class="btn btn-primary">Add Project</a>
</div>


<div class="row">
    <div class="col-md-12">
        <table class="table">
            <tr>
                <th># ID</th>
                <th>Start Date</th>
                <th>Credits</th>
                <th>End Date</th>
                <th>Function</th>
            </tr>
            @foreach (var Obj_project in Model)
            {
            <tr>
                <td>@Obj_project.iId</td>
                <td>@Obj_project.dtStartDate</td>
                <td>@Obj_project.iCredits</td>
                <td>@Obj_project.dtEndData</td>
                <td>
                    <a href="/Project_/Delete_Project/@Obj_project.iId" class="btn btn-danger">Delete</a>
                </td>
            </tr>
            }
        </table>
    </div>
</div>