Coding_Challenge/Controllers/Assignment_Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Coding_Challenge.Models;
using Coding_Challenge.Models.AssignmentViewModels;

namespace Coding_Challenge.Controllers
{
    public class Assignment_Controller : Controller
    {
        public ActionResult list_Assignment()
        {
            List<cls_ListAssignmentViewModel> lst;
            using (Coding_ChallengeEntities db = new Coding_ChallengeEntities())
            {
                

                lst = (from Obj_Assignment in db.UserProjects
                       select new cls_ListAssignmentViewModel
                       {
                           iId = Obj_Assignment.id,
                           iUserId = Obj_Assignment.UserId,
                           iProjectId = Obj_Assignment.ProjectId,
                           bIsActive = Obj_Assignment.IsActive,
                           dtAssignedDate = Obj_Assignment.AssignedDate
                       }).ToList();
            }

            return View(lst);
        }

        public ActionResult Add_Assignment()
        {
            using (Coding_ChallengeEntities db = new Coding_ChallengeEntities())
            {
                var userInformation = new SelectList(db.Users.ToList(), "id", "FirstName");
                ViewBag.listUser = userInformation;

                var projectInformation = new SelectList(db.Projects.ToList(), "id", "id");
                ViewBag.listProject = projectInformation;
            }
                
            return View();
        }

        [HttpPost]
        public ActionResult Add_Assignment(cls_AddAssignmentViewModel model)
        {
            try
            {
                  
                using (Coding_ChallengeEntities db = new Coding_ChallengeEntities())
                {

                    var userInformation = new SelectList(db.Users.ToList(), "id", "FirstName");
                    ViewBag.listUser = userInformation;

                    var projectInformation = new SelectList(db.Projects.ToList(), "id", "id");
                    ViewBag.listProject = projectInformation;

                    if (ModelState.IsValid)
                    {
                        var Obj_Assignment = new UserProject();
                        Obj_Assignment.UserId = model.iUserId;
                        Obj_Assignment.ProjectId = model.iProjectId;
                        Obj_Assignment.IsActive = model.bIsActive == "1";
                        Obj_Assignment.AssignedDate = model.dtAssignedDate;

                        db.UserProjects.Add(Obj_Assignment);
                        db.SaveChanges();
                        return Redirect("/Assignment_/list_Assignment");
                    }
                        
                }

                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpGet]
        public ActionResult Delete_Assignment(int id)
        {
            using (Coding_ChallengeEntities db = new Coding_ChallengeEntities())
            {
                var Obj_Assignment = db.UserProjects.Find(id);
                db.UserProjects.Remove(Obj_Assignment);
                db.SaveChanges();
            }
            return Redirect("/Assignment_/list_Assignment");
        }
    }
}

Coding_Challenge/Views/Assignment_/Add_Assignment.cshtml
@model Coding_Challenge.Models.AssignmentViewModels.cls_AddAssignmentViewModel
@{
    ViewBag.Title = "Add_Assignment";

    
}

<h2></h2>

@using (Html.BeginForm("Add_Assignment", "Assignment_", FormMethod.Post))
{
    <div class="row" style="margin: 50px;">
        <h2>Add a New Assignment</h2>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="row">
                @Html.LabelFor(d => d.iUserId)<br />
                @Html.DropDownListFor(d => d.iUserId, (SelectList)ViewBag.listUser, new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.iUserId, null, new { @class = "red" })
            </div>
            <div class="row">
                @Html.LabelFor(d => d.iProjectId)<br />
                @Html.DropDownListFor(d => d.iProjectId, (SelectList)ViewBag.listProject, new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.iProjectId, null, new { @class = "red" })
            </div>
            <div class="row">
                @Html.LabelFor(d => d.bIsActive)<br />
                @Html.DropDownListFor(d => d.bIsActive, new List<SelectListItem>
                {
                   new SelectListItem{ Text="False", Value = "0"},
                   new SelectListItem{ Text="True", Value = "1" },
                }, new { @class = "form-control" })  <br />
                @Html.ValidationMessageFor(d => d.bIsActive, null, new { @class = "red" })
            </div>
            <div class="row">
                @Html.LabelFor(d => d.dtAssignedDate)<br />
                @Html.EditorFor(d => d.dtAssignedDate, "", new { @class = "form-control" })<br />
                @Html.ValidationMessageFor(d => d.dtAssignedDate, null, new { @class = "red" })
            </div>
        </div>

        <div class="col-md-12" style="text-align:right;padding:5px">
            <input value="Save Assignment" type="submit" class="btn btn-primary" />
        </div>
    </div>
}

Coding_Challenge/Views/Assignment_/Delete_Assignment.cshtml
@{
    ViewBag.Title = "Delete_Assignment";
}

<h2>Delete_Assignment</h2>

Coding_Challenge/Views/Assignment_/list_Assignment.cshtml
@model List<Coding_Challenge.Models.AssignmentViewModels.cls_ListAssignmentViewModel>
@{
    ViewBag.Title = "list_Assignment";
}

<div class="row" style="margin: 50px;">
    <h2>Assignments</h2>
</div>


<div class="row" style="text-align:right; padding:5px">
    <a href="../Assignment_/Add_Assignment" class="btn btn-primary">Add Assigment</a>
</div>


<div class="row">
    <div class="col-md-12">
        <table class="table">
            <tr>
                <th># ID</th>
                <th>User Name</th>
                <th>Project ID</th>
                <th>Is Active?</th>
                <th>Assignment Date</th>
                <th>Function</th>
            </tr>
            @foreach (var Obj_assigment in Model)
            {
            <tr>
                <td>@Obj_assigment.iId</td>
                <td>@Obj_assigment.iUserId</td>
                <td>@Obj_assigment.iProjectId</td>
                <td>@Obj_assigment.bIsActive</td>
                <td>@Obj_assigment.dtAssignedDate</td>
                <td>
                    <a href="/Assignment_/Delete_Assignment/@Obj_assigment.iId" class="btn btn-danger">Delete</a>
                </td>
            </tr>
            }
        </table>
    </div>
</div>