Coding_Challenge/Models/User.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coding_Challenge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.UserProjects = new HashSet<UserProject>();
        }
    
        public int id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProject> UserProjects { get; set; }
    }
}

Coding_Challenge/Controllers/User_Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Coding_Challenge.Models;
using Coding_Challenge.Models.ViewModels;

namespace Coding_Challenge.Controllers
{
    public class User_Controller : Controller
    {
        // GET: User_
        public ActionResult Index()
        {
            List<cls_listUserViewModel> lst;
            using (Coding_ChallengeEntities db = new Coding_ChallengeEntities())
            {
                lst = (from user in db.Users
                    select new cls_listUserViewModel
                    {
                        iId = user.id,
                        sFirtName = user.FirstName,
                        sLastName = user.LastName
                    }).ToList();
            }

            return View(lst);
        }
        
        public ActionResult Add_User()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add_User(cls_AddUserViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (Coding_ChallengeEntities db = new Coding_ChallengeEntities())
                    {
                        var Obj_user = new User();
                        Obj_user.FirstName = model.sFirtName;
                        Obj_user.LastName = model.sLastName;

                        db.Users.Add(Obj_user);
                        db.SaveChanges();
                    }

                    return Redirect("/User_/Index");
                }

                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpGet]
        public ActionResult Delete_User(int id)
        {
            using (Coding_ChallengeEntities db = new Coding_ChallengeEntities())
            {
                var Obj_User = db.Users.Find(id);
                db.Users.Remove(Obj_User);
                db.SaveChanges();
            }
            return Redirect("/User_/Index");
        }
    }
}

Coding_Challenge/Views/User_/Add_User.cshtml
@model Coding_Challenge.Models.ViewModels.cls_AddUserViewModel
@{
    ViewBag.Title = "Add_User";
}
<!--<form action="" method="post"></form>-->

@using (Html.BeginForm("Add_User", "User_", FormMethod.Post))
{
    <div class="row" style="margin: 50px;">
        <h2>Add a New User</h2>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="row">
                @Html.LabelFor(d => d.sFirtName)
                @Html.TextBoxFor(d => d.sFirtName, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.sFirtName, null, new { @class = "red" })
            </div>
            <div class="row">
                @Html.LabelFor(d => d.sLastName)
                @Html.TextBoxFor(d => d.sLastName, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.sLastName, null, new { @class = "red" })
            </div>
        </div>

        <div class="col-md-12" style="text-align:right;padding:5px">
            <input value="Save User" type="submit" class="btn btn-primary" />
        </div>
    </div>
}

Coding_Challenge/Views/User_/Delete_User.cshtml
@{
    ViewBag.Title = "Delete_User";
}

<h2>Delete_User</h2>

Coding_Challenge/Views/User_/Index.cshtml
@model List<Coding_Challenge.Models.ViewModels.cls_listUserViewModel>
@{
    ViewBag.Title = "Mis datos";
}

<div class="row" style="margin: 50px;">
    <h2>Users</h2>
</div>

<div class="row" style="text-align:right; padding:5px">
    <a href="../User_/Add_User" class="btn btn-primary">Add User</a>
</div>


<div class="row">
    <div class="col-md-12">
        <table class="table">
            <tr>
                <th># ID</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Function</th>
            </tr>
            @foreach (var user in Model)
            {
                <tr>
                    <td>@user.iId</td>
                    <td>@user.sFirtName</td>
                    <td>@user.sLastName</td>
                    <td>
                        <a href="/User_/Delete_User/@user.iId" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>